ENVIRONMENT:
  NUM_GPU: 4

DATA_LOADER:
  TEST_IMAGE_DIR: '/data3/workspace/inputs/'
  TEST_SERIES_IDS_TXT: None
  LABEL_INDEX: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13]
  LABEL_NUM: [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]
  LABEL_NAME: ['Liver', 'Right Kidney', 'Spleen', 'Pancreas', 'Aorta', 'Inferior Vena Cava', 'Right Adrenal Gland', 'Left Adrenal Gland', 'Gallbladder', 'Esophagus', 'Stomach', 'Duodenum', 'Left kidney']
  IS_NORMALIZATION_HU: True
  IS_NORMALIZATION_DIRECTION: True
  WINDOW_LEVEL: [-400, 400]
  EXTEND_SIZE: 20

COARSE_MODEL:
  META_ARCHITECTURE: 'UNet'
  INPUT_SIZE: [160, 160, 160]
  NUM_CLASSES: 13
  NUM_CHANNELS: [8, 16, 32, 64, 128]
  ENCODER_CONV_BLOCK: 'ResFourLayerConvBlock'
  DECODER_CONV_BLOCK: 'ResTwoLayerConvBlock'
  CONTEXT_BLOCK: None
  NUM_DEPTH: 4
  IS_PREPROCESS: True
  IS_POSTPROCESS: False
  IS_DYNAMIC_EMPTY_CACHE: True
  WEIGHT_DIR: './FlareSeg/model_weights/base_coarse_model/best_model.pt'

FINE_MODEL:
  META_ARCHITECTURE: 'EfficientSegNet'
  AUXILIARY_TASK: False
  AUXILIARY_CLASS: 1
  INPUT_SIZE: [192, 192, 192]
  NUM_CLASSES: 13
  NUM_BLOCKS: [2, 2, 2, 2, 2]
  DECODER_NUM_BLOCK: 1
  NUM_CHANNELS: [16, 32, 64, 128, 256]
  ENCODER_CONV_BLOCK: 'ResBaseConvBlock'
  DECODER_CONV_BLOCK: 'AnisotropicConvBlock'
  CONTEXT_BLOCK: 'AnisotropicAvgPooling'
  NUM_DEPTH: 4
  IS_PREPROCESS: True
  IS_POSTPROCESS: True
  IS_DYNAMIC_EMPTY_CACHE: True
  WEIGHT_DIR: './FlareSeg/model_weights/efficient_fine_model/best_model.pt'

TESTING:
  COARSE_MODEL_WEIGHT_DIR: './FlareSeg/model_weights/base_coarse_model/best_model.pt'
  FINE_MODEL_WEIGHT_DIR: './FlareSeg/model_weights/efficient_fine_model/best_model.pt'
  NUM_WORKER: 4
  BATCH_SIZE: 1
  IS_FP16: True
  SAVER_DIR: /data3/workspace/outputs/
  IS_SAVE_MASK: True
  IS_POST_PROCESS: True
  IS_SYNCHRONIZATION: False
  OUT_RESAMPLE_MODE: 3
